version: '3'
services:
  backend:
    build:
      context: ./solar_watch_backend
    image: sw_backend_img
    container_name: sw_backend_container
    depends_on: 
      - db
    ports:
      - "5000:80"
    environment:
      - SW_DB_HOST=db,1433
    env_file:
      - ./solar_watch_backend/.env

  frontend:
    build:
      context: ./solar_watch_frontend
    image: sw_frontend_img
    container_name: sw_frontend_container
    environment:
      - EXAMPLE_BACKEND_URL=http://backend:80
    ports:
      - "5173:5173"

  db:
    image: mcr.microsoft.com/mssql/server
    restart: always
    container_name: sw_db_container
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
    ports:
      - "1433:1433"
volumes:
  mssql_data:
